#!/usr/bin/env ruby

# Twiwt:Blog / jugyo : spork でサクサク RSpec on Rails3
# http://blog.twiwt.org/e/cafcfe
require 'drb'
require 'pry'

begin
  begin
    DRb.start_service("druby://localhost:0")
  rescue SocketError, Errno::EADDRNOTAVAIL
    DRb.start_service("druby://:0")
  end
  $spec_server = DRbObject.new_with_uri("druby://127.0.0.1:8989")
rescue DRb::DRbConnError
  err.puts "No DRb server is running. Running in local process instead ..."
end

def rspec(file)
  $spec_server.run(["--color", "--format", "Fuubar", file], STDERR, STDOUT)
end

puts <<DESC

Example:
> rspec 'vendor/engines/town_stories/spec'

DESC

Pry.start
